import cv2
img = cv2.imread('/home/vipul/goku1.jpg')
img2 = cv2.resize(img, (500, 300))
cv2.imshow("output",img2)
imCopy = img2.copy()
gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
cv2.imshow("gray",gray)
blur = cv2.GaussianBlur(gray, (5, 5), 0)
cv2.imshow("blur",blur)
ret, thresh1 = cv2.threshold(blur, 10, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
cv2.imshow("Threshold", thresh1)
ret, thresh2 = cv2.threshold(img2, 100, 255, cv2.THRESH_TRUNC)
cv2.imshow("threshold truncated",thresh2)
contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(imCopy, contours, -1, (0, 255, 0))
cv2.imshow('Contour', imCopy)
cv2.waitKey(0)
